description = "This is JohanChane's blog"

# Author Configuration
[author]
  name = "JohanChane"
  email = ""
  link = "https://github.com/johanchane"
  avatar = ""

[app]
  # modern SVG favicon to use in place of older style .png and .ico files
  svgFavicon = "favicon.png"
[header.title]
  # URL of the LOGO
  #logo = "favicon.png"
  logo = "https://github.com/JohanChane/my-blog/blob/main/static/favicon.png?raw=true"  # 这是必须要用 URL
# Home page profile
[home.profile]
  # subtitle shown in home page (HTML format is supported)
  subtitle = "This is my blog"
# FixIt 0.2.16 | CHANGED Social config about the author
[social]
  GitHub = "johanchane"
  RSS = false
[page.comment]
  enable = true
  # FixIt 0.2.14 | NEW Giscus comments config
  [page.comment.giscus]
    enable = true
    repo = "JohanChane/my-blog"
    repoId = "R_kgDOOYN21w"
    category = "Announcements"
    categoryId = "DIC_kwDOOYN2184CpEo7"
    mapping = "pathname"
    origin = "https://giscus.app" # FixIt NEW | 0.3.7 Or set it to your self-hosted domain
    strict = "0" # FixIt NEW | 0.2.18
    term = ""
    reactionsEnabled = "1"
    emitMetadata = "0"
    inputPosition = "top" # ["top", "bottom"]
    lang = "zh-CN"
    lightTheme = "light"
    darkTheme = "dark"
    lazyLoad = true
